# Generated by Django 3.0.1 on 2019-12-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('payday', models.DateTimeField(verbose_name='pay date')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
